server:
  port: 8003

spring:
  profiles:
    # \u751F\u4EA7\u73AF\u5883
    active: dev
  # \u8FDE\u63A5\u4FE1\u606F
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: liao
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    # \u8FDE\u63A5\u6C60
    druid:
      # \u521D\u59CB\u8FDE\u63A5\u6570
      initialSize: 5
      # \u6700\u5C0F\u8FDE\u63A5\u6C60\u6570\u91CF
      minIdle: 10
      # \u6700\u5927\u8FDE\u63A5\u6C60\u6570\u91CF
      maxActive: 20
      # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
      maxWait: 60000
      # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      timeBetweenEvictionRunsMillis: 60000
      # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      minEvictableIdleTimeMillis: 300000
      # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5927\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      maxEvictableIdleTimeMillis: 900000
      # \u914D\u7F6E\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # \u8BBE\u7F6E\u767D\u540D\u5355\uFF0C\u4E0D\u586B\u5219\u5141\u8BB8\u6240\u6709\u8BBF\u95EE
        allow:
        url-pattern: /druid/*
        # \u63A7\u5236\u53F0\u7BA1\u7406\u7528\u6237\u540D\u548C\u5BC6\u7801
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # \u6162SQL\u8BB0\u5F55
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #\u8FDE \u63A5\u8D85\u65F6\u65F6\u95F4
    timeout: 30000

# mybatis
mybatis:
  mapperClassScan: com.liao.view.dao
  type-aliases-package: com.liao.view.entity
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
# mybatis-plus
mybatis-plus:
  mapperClassScan: com.liao.view.dao
  type-aliases-package: com.liao.view.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    # \u65E5\u5FD7\u6253\u5370
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: ID_WORKER
      # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-delete-value: 1
      # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
      logic-not-delete-value: 0


